[package]
name = "blockchain_rust"
authors = ["LEVI_104 <0xlevi104.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
data-encoding = "2.3.2"
num-bigint = "0.4.3"